AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an S3 bucket on the application account.
Parameters:
  UAI:
    Type: String
  AppName:
    Type: String
  AppROLE:
    Type: String
    Default: "app"
  ENV:
    Type: String
    Default: "dev"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Tags (Mandatory)
        Parameters:
          - AppName
          - AppROLE
          - ENV
          - UAI
Resources:
  GetBucketNAME:
    Type: Custom::GetCFOutputs
    Properties:
      ServiceToken: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - 'GetCFOutputs'
      stackArn: !GetAtt 'CreateBucketForApplication.CloudformationStackArn'

  CreateBucketForApplication:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
     ProductName: "S3Bucket"
     ProvisioningArtifactName: "{{resolve:ssm:/ServiceCatalog/S3Bucket/LatestVersion:1}}"
     ProvisioningParameters:
      - Key: "app"
        Value: !Ref AppName
      - Key: "uai"
        Value: !Ref UAI
      - Key: "role"
        Value: !Ref AppROLE
      - Key: "env"
        Value: !Ref ENV
      - Key: "DataClassification"
        Value: 'Temporary'
      - Key: "S3BucketName"
        Value:  
            'Fn::Transform':
             - Name: 'String'
               Parameters:
                 InputString: !Join ["",[!Ref "AppName","-",!Ref "ENV","-","src"]]
                 Operation: Lower
Outputs:
 BucketName:
  Description:  Bucket Name
  Value: !GetAtt GetBucketNAME.S3BucketName
  Export:
    Name: !Join
      - '-'
      - - 'Bucket'
        - !Ref ENV
        - 'src'
