AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a managed policy Service Catalog 
Parameters:
  AppName:
    Type: String
  Policy:
    Type: String

Resources:
  CreateManagedPolicy:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
     ProductName: "Managed-Policy"
     ProvisioningArtifactName: "{{resolve:ssm:/ServiceCatalog/Managed-Policy/LatestVersion:1}}"
     ProvisioningParameters:
      - Key: "Policy"
        Value: !Ref Policy
      - Key: "app"
        Value: !Ref AppName
